#"name": (energy, hydration)

items_dict = {
    'Emelya rye croutons': (10, -10),
    'Army crackers': (10, -5),
    'Rye croutons': (20, -10),
    'Slickers chocolate bar': (30, -15),
    'Alyonka chocolate bar': (35, -15),
    'Pack of oat flakes': (40, -13),
    'Pack of sugar': (70, -45),
    'Can of condensed milk': (75, -65),
    'Jar of DevilDog mayo': (100, -99),
    'Can of beef stew (Small)': (45, -5),
    'Can of herring': (47, -3),
    'Can of pacific saury': (48, -2),
    'Can of beef stew (Large)': (50, -5),
    'Can of humpback salmon': (50, -5),
    'Salty Dog beef sausage': (50, -5),
    'Can of sprats': (55, -5),
    'Can of green peas': (35, 5),
    'Pack of Tarker dried meat': (55, -5),
    'Pack of instant noodles': (25, -10),
    'Can of squash spread': (40, 0),
    'MRE ration pack': (70, 0),
    'Iskra ration pack': (80, 0),
    'Can of Ice Green tea': (0, 15),
    'Can of TarCola soda': (5, 15),
    'Pack of apple juice': (5, 25),
    'Can of Hot Rod energy drink': (10, 20),
    'Can of Max Energy energy drink': (12, 20),
    'Pack of Vita juice': (8, 28),
    'Pack of Grand juice': (6, 30),
    'Pack of Russian Army pineapple juice': (8, 30),
    'Can of RatCola soda': (20, 20),
    'Pack of milk': (20, 30),
    'Bottle of Pevko Light beer': (10, 40),
    'Emergency Water Ration': (5, 50),
    'Bottle of water (0.6L)': (0, 60),
    'Bottle of Norvinskiy Yadreniy premium kvass (0.6L)': (15, 65),
    'Aquamari water bottle with filter': (20, 100),
    'Canister with purified water': (25, 100),
    'Bottle of Dan Jackiel whiskey': (10, -35),
    'Bottle of Tarkovskaya vodka': (0, -50),
    'Bottle of Fierce Hatchling moonshine': (20, -10),
}