#"name": (energy, hydration)

items_dict = {
    'Emelya rye croutons': [10, -10, 'Emelya_rye_croutons'],
    'Army crackers': [10, -5, 'Army_Crackers'],
    'Rye croutons': [20, -10, 'Rye_croutons'],
    'Slickers chocolate bar': [30, -15, 'Slickers_bar'],
    'Alyonka chocolate bar': [35, -15, 'Alyonka_chocolate_bar'],
    'Pack of oat flakes': [40, -13, 'Pack_of_oat_flakes'],
    'Pack of sugar': [70, -45, 'Pack_of_sugar'],
    'Can of condensed milk': [75, -6, 'Condensed_milk'],
    'Jar of DevilDog mayo': [100, -99, 'Jar_of_DevilDog_mayo'],
    'Can of beef stew [Small]': [45, -5, 'Can_of_beef_stew'],
    'Can of herring': [47, -3, 'Can_of_herring'],
    'Can of pacific saury': [48, -2, 'Can_of_pacific_saury'],
    'Can of beef stew [Large]': [50, -5, 'Can_of_delicious_beef_stew'],
    'Can of humpback salmon': [50, -5, 'Humpback_salmon'],
    'Salty Dog beef sausage': [50, -5, 'salty_dog_beef_sausage'],
    'Can of sprats': [55, -5, 'Can_of_sprats'],
    'Can of green peas': [35, 5, 'Can_of_green_peas'],
    'Pack of Tarker dried meat': [55, -5, 'pack_of_tarker_dried_meat'],
    'Pack of instant noodles': [25, -10, 'pack_of_instant_noodles'],
    'Can of squash spread': [40, 0, 'Squash_spread'],
    'MRE ration pack': [70, 0, 'MRE_lunch_box'],
    'Iskra ration pack': [80, 0, 'Iskra_lunch_box'],
    'Can of Ice Green tea': [0, 15, 'Green_Ice'],
    'Can of TarCola soda': [5, 15, 'TarCola'],
    'Pack of apple juice': [5, 25, 'Apple_juice'],
    'Can of Hot Rod energy drink': [10, 20, 'Hot_Rod'],
    'Can of Max Energy energy drink': [12, 20, 'Max_energy'],
    'Pack of Vita juice': [8, 28, 'Vita_juice'],
    'Pack of Grand juice': [6, 30, 'Grand_juice'],
    'Pack of Russian Army pineapple juice': [8, 30, 'Russian_Army_pineapple_juice'],
    'Can of RatCola soda': [20, 20, 'can_of_ratcola'],
    'Pack of milk': [20, 30, 'Pack_of_milk'],
    'Bottle of Pevko Light beer': [10, 40, 'bottle_of_beer_pevko_light'],
    'Emergency Water Ration': [5, 50, 'emergency_water_ration'],
    'Bottle of water [0.6L]': [0, 60, '0.6L_water_bottle'],
    'Bottle of Norvinskiy Yadreniy premium kvass [0.6L]': [15, 65, 'premium_kvass_norvinskiy_yadreniy_0.6l_bottle'],
    'Aquamari water bottle with filter': [20, 100, 'Water_bottle_with_a_filter_Aquamari'],
    'Canister with purified water': [25, 100, 'purified_water'],
    'Bottle of Dan Jackiel whiskey': [10, -3, 'Bottle_of_Dan_Jackiel_Whiskey'],
    'Bottle of Tarkovskaya vodka': [0, -50, 'Bottle_of_vodka_Tarkovskaya'],
    'Bottle of Fierce Hatchling moonshine': [20, -10, 'fierce_hatchling_moonshine'],
}

all_provision_urls = [
'Green_Ice',
'Squash_spread',
'Can_of_green_peas',
'Rye_croutons',
'Pack_of_oat_flakes',
'TarCola',
'Emelya_rye_croutons',
'Pack_of_milk',
'Can_of_pacific_saury',
'Condensed_milk',
'Can_of_sprats',
'Can_of_delicious_beef_stew',
'can_of_ratcola',
'Jar_of_DevilDog_mayo',
'Can_of_beef_stew',
'fierce_hatchling_moonshine',
'Iskra_lunch_box',
'Grand_juice',
'salty_dog_beef_sausage',
'premium_kvass_norvinskiy_yadreniy_0.6l_bottle',
'Russian_Army_pineapple_juice',
'Bottle_of_vodka_Tarkovskaya',
'Pack_of_sugar',
'Hot_Rod',
'Alyonka_chocolate_bar',
'Water_bottle_with_a_filter_Aquamari',
'Bottle_of_Dan_Jackiel_Whiskey',
'bottle_of_beer_pevko_light',
'Apple_juice',
'Vita_juice',
'Can_of_herring',
'0.6L_water_bottle',
'pack_of_instant_noodles',
'Humpback_salmon',
'MRE_lunch_box',
'Max_energy',
'purified_water',
'Slickers_bar',
'Army_Crackers',
'pack_of_tarker_dried_meat',
'emergency_water_ration'
]